[package]
name = "legion-common"
version = "0.0.1"
authors = ["Marek Counts <marek@thenullchannel.dev>"]
edition = "2018"
description = "common components shared by all things legion"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8.24"
serde_derive = "1.0"
serde_cbor = "0.9"
chrono = { version = "0.4", features = ["serde"] }
whoami = "0.5.2"
